sudo: required
services:
  - docker

before_install: 
  - docker build -t frontend/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rontend/docker-reac npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-30647662747"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"